sudo: required
dist: trusty      
language: cpp

compiler:
  - gcc

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - ubuntu-sdk-team
    packages:
     - g++-6
     - gcc-6
     - qt5-default
     - qttools5-dev-tools

script:
 - qmake -project
 - qmake openrcon.pro
 - make
