sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toouire
before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get -qq update
 - sudo apt-get install -y qt5-default qttools5-dev-tools

script:
 - qmake -project
 - qmake openrcon.pro
 - make
