sudo: required
dist: trusty      
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: 
           - ubuntu-toolchain-r-test
           - ubuntu-sdk-team
          packages: 
          - g++-6
          - qt5-default
          - qttools5-dev-tools
      env: COMPILER=g++-6

    - compiler: clang
      addons:
        apt:
          sources:
           - llvm-toolchain-3.7
           - ubuntu-sdk-team
          packages: 
           - clang-3.7
           - qt5-default
           - qttools5-dev-tools
      env: COMPILER=clang++-3.7
      
script:
 - qmake -project
 - qmake openrcon.pro
 - make CXX=$COMPILER
