sudo: required
dist: trusty      
language: cpp

compiler:
  - gcc-6

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - ubuntu-sdk-team
    packages:
     - g++-6
     - qt5-default
     - qttools5-dev-tools

before_install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
 - qmake -project
 - qmake openrcon.pro
 - make
