sudo: required
dist: trusty      
language: cpp

compiler:
  - gcc-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get -qq update
 - sudo apt-get install -y qt5-default qttools5-dev-tools

script:
 - qmake -project
 - qmake openrcon.pro
 - make
