sudo: required
dist: trusty      
language: cpp

compiler:
  - gcc-6

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - ubuntu-sdk-team
    packages:
     - g++-6
     - qt5-default
     - qttools5-dev-tools

before_install:
 - sudo add-apt-repository --yes /ppa
 - sudo apt-get -qq update
 - sudo apt-get install -y qt5-default qttools5-dev-tools

script:
 - qmake -project
 - qmake openrcon.pro
 - make
